### ISSUE TITLE
About age_train.txt

### ISSUE THREAD

**Issue by zyh-uaiaaaa** [Li-Wanhua/POEs#2]
Hello, xk-huang and Li-Wanhua. It's really an excellent work.
I wonder if you can upload the age_train.txt and age_test.txt which would save lots of my time as I'm a beginner to age estimation area. Thanks a lot for your help.

**Comment by Li-Wanhua** [comment]
Hi, thanks for your attention to our work!
You can find the data in https://talhassner.github.io/home/projects/Adience/Adience-data.html, which also provides the split of five folds. We use the standard five-fold cross-validation protocol, which uses four folds for training and the left fold for testing. Since we don't own the database, we don't include these files for legal issues. But we believe the above information gives a clear path.

**Comment by zyh-uaiaaaa** [comment]
Thanks for your help!
